### ISSUE TITLE
Error C920181A after 'udsploit: UDS_Unbind'

### ISSUE THREAD

**Issue by MateuszPG** [smealum/udsploit#14]
What should I do to make it work?

**Comment by fernando-freitas-alves** [comment]
Same issue here. I'm in 11.4.

**Comment by maese-crom** [comment]
@MateuszPG 
Solved. I got that error and I just made this:
-Enter in Recovery mode by pressing L+R+A+D-Up while turning on the 3DS
-Check if Wi-Fi is turned on
-Copying again the files
I did those three things at the same time. I don't know what really solves it.
Hope I helped you!!!
P.D: @fernando-freitas-alves I think you already know this doesn't work on 11.4

**Comment by miinow** [comment]
Same issue. Mine is on 11.5.

**Comment by yellows8** [comment]
README

**Comment by stampylongr** [comment]
I'm sorry, I must be misunderstanding this. I've done ```L+R+A+D-Up``` to enter recovery mode, put it just tells me to update my system.

**Comment by chronoss09** [comment]
> README

nothig on the readme....
same issue 11.4
